### ISSUE TITLE
Can`t stop or remove service

### ISSUE THREAD

**Issue by ergcode** [Postuf/Toroxy#2]
Как этот кусок коровьево навоза нормально удалить или остановить? 
Вы наверное думали когда писали код, что не нужно 24/7 использовать TOR?

**Comment by ergcode** [comment]
Или мне теперь нужно раскапывать скрипт, чтобы увидеть, что он нарушил в ОС?

**Comment by Ririconj** [comment]
Остановка происходит точно так же, как и запуск systemd-сервиса. Для удаления предусмотрен отдельный скрипт, который включает в себя остановку сервиса. Об этом написано в README:

1. https://github.com/Postuf/Toroxy#how-to-use  (остановка)
2. https://github.com/Postuf/Toroxy#how-to-uninstall (удаление)

Если после этих операций следы Toroxy все равно остались в системе, пришлите свои таблицы системного файрвола (netfilter) `nat` и `filter`, для того, чтобы точно подтвердить, что проблема с нашей стороны:

1. `iptables -L`
2. `iptables -t nat -L`

Также расскажите нам о других "огромаднейших логических дырах" - будем рады поправить

**Comment by ergcode** [comment]
Помогло решение с установить, удалить. И удалить все следы tor в системе. 
Похоже проблема именно в тор.

**Comment by ergcode** [comment]
Про логические дыры - должна быть возможность остановить навсегда основной и взаимосвязанные сервисы. 

Извиняюсь за столь резкое высказывание ранее. Но необычное поведение при старте системы попило мне не мало крови.

**Comment by Ririconj** [comment]
Остановка взаимосвязанных сервисов (Tor) могла бы оказаться еще большей проблемой, потому что на момент установки эти сервисы уже могли присутствовать в системе с определенной конфигурацией (включающей другие зависимые от Tor сервисы). Точки соприкосновения Toroxy и Tor заключаются в:

1. Изменении конфигурационного файла `torrc` с целью включения `transparent proxy` и DNS
2. Изменении системных настроек DNS
3. Добавлении списка правил в таблицу `nat` (PREROUTING) системного файрвола для перенаправления трафика во включенный `transparent proxy`

При остановке сервиса откат каждого из 3 пунктов происходил неявно, теперь производим более очевидную чистку - https://github.com/Postuf/Toroxy/commit/c5fea47f95f92cb1b9f1e98c22ea1f56e92655f2
