### ISSUE TITLE
Эта программа запускается сама, когда ей вздумается.

### ISSUE THREAD

**Issue by bogdasar1985** [Postuf/Toroxy#4]
К тому-же, невозможно нормально следить за состоянием сервиса. Хоть бы плашка в трее была.

**Comment by Ririconj** [comment]
Toroxy работает как systemd сервис с автозапуском при старте системы (systemd запускается на 3 уровне инициаллизации `WantedBy=multi-user.target`). В ходе работы системы за ним можно наблюдать как и за любым другим systemd-сервисом (через утилиты `service` и\или `systemctl`).
